"""Add venue_genres field to Venue model

Revision ID: 6da6e55fd5f5
Revises: 44914a2ecf88
Create Date: 2023-06-25 11:15:14.051522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da6e55fd5f5'
down_revision = '44914a2ecf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    op.drop_table('artist_genre_table')
    op.drop_table('venue_genre_table')
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))
        batch_op.alter_column('seeking_description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_genres', sa.String(length=120), nullable=True))
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('venue_genres')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('genres')

    op.create_table('venue_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='venue_genre_table_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venue_genre_table_venue_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id', name='venue_genre_table_pkey')
    )
    op.create_table('artist_genre_table',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist_genre_table_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='artist_genre_table_genre_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'artist_id', name='artist_genre_table_pkey')
    )
    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey')
    )
    # ### end Alembic commands ###
