"""Add genres column to Venue table

Revision ID: a1a3639ebd9e
Revises: 45e569cb3b95
Create Date: 2023-06-26 12:07:27.267504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a3639ebd9e'
down_revision = '45e569cb3b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=False))
        batch_op.drop_column('venue_genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
